# noesis home-manager module.
#
# Wires up:
#   - the rwkv.cpp inference binary (host-tuned) into $HOME
#   - a user-scope systemd service that runs the noesis-runtime supervisor,
#     which in turn spawns the model process (rwkv.cpp or Ollama-child).
#
# The runtime binary itself lives in `runtime/target/release/noesis-runtime`
# (built by the workspace Cargo build; see `flake.nix` package output).
#
# Usage from ~/.config/home-manager/flake.nix:
#   inputs.noesis.url = "path:/home/vaniello/Desktop/projects/noesis";
#   inputs.noesis.inputs.nixpkgs.follows = "nixpkgs";
#   ... modules = [ noesis.homeModules.default ... ];
# then in home.nix:
#   services.noesis-runtime.enable = true;

self:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.noesis-runtime;
  system = pkgs.system;
  runtimePkg = self.packages.${system}.noesis-runtime;
  rwkvCppPkg = self.packages.${system}.rwkv-cpp;
in
{
  options.services.noesis-runtime = {
    enable = lib.mkEnableOption "noesis persistent cognitive runtime";

    autoStart = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Start noesis-runtime on graphical-session.target. Disabled by default
        because Phase A / Phase B are still experimental; flip to true only
        after A0.3 sustained-idle verdict lands.
      '';
    };

    modelPath = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/.cache/huggingface/hub";
      description = "Path where RWKV-7 checkpoints are cached.";
    };

    statePath = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/.local/share/noesis";
      description = "Root for noesis persistent state (memory zones, logs).";
    };

    inferenceBackend = lib.mkOption {
      type = lib.types.enum [ "rwkv-cpp" "ollama" ];
      default = "rwkv-cpp";
      description = ''
        Which inference backend the supervisor spawns as a child.
        `rwkv-cpp` uses the host-tuned CPU binary from this flake;
        `ollama` delegates to a system-wide ollama daemon.
      '';
    };

    memoryMax = lib.mkOption {
      type = lib.types.str;
      default = "6G";
      description = "systemd MemoryMax for the runtime process.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [
      runtimePkg
    ] ++ lib.optional (cfg.inferenceBackend == "rwkv-cpp") rwkvCppPkg;

    home.activation.noesisStateDirs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      $DRY_RUN_CMD mkdir -p ${cfg.statePath}/input_events
      $DRY_RUN_CMD mkdir -p ${cfg.statePath}/system_obs
      $DRY_RUN_CMD mkdir -p ${cfg.statePath}/personal_vault
      $DRY_RUN_CMD mkdir -p ${cfg.statePath}/session_scratch
      $DRY_RUN_CMD mkdir -p ${cfg.statePath}/logs
    '';

    xdg.configFile."noesis/runtime.toml".text = ''
      # noesis runtime config. Regenerated by home-manager; edit the module
      # rather than this file.

      state_path = "${cfg.statePath}"
      model_path = "${cfg.modelPath}"
      inference_backend = "${cfg.inferenceBackend}"

      ${lib.optionalString (cfg.inferenceBackend == "rwkv-cpp") ''
        [rwkv_cpp]
        binary = "${rwkvCppPkg}/bin/rwkv-cpp"
        threads = 4
      ''}

      ${lib.optionalString (cfg.inferenceBackend == "ollama") ''
        [ollama]
        endpoint = "http://127.0.0.1:11434"
      ''}
    '';

    systemd.user.services.noesis-runtime = {
      Unit = {
        Description = "noesis persistent cognitive runtime";
        After = [ "graphical-session.target" ];
        PartOf = [ "graphical-session.target" ];
      };
      Service = {
        ExecStart = "${runtimePkg}/bin/noesis-runtime";
        Environment = [
          "NOESIS_CONFIG=%h/.config/noesis/runtime.toml"
          "RUST_LOG=info"
        ];
        Restart = "on-failure";
        RestartSec = "5s";
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ReadWritePaths = [ cfg.statePath ];
        MemoryMax = cfg.memoryMax;
      };
      Install = lib.mkIf cfg.autoStart {
        WantedBy = [ "graphical-session.target" ];
      };
    };
  };
}
