# noesis NixOS system module.
#
# Declarative form of `runtime/contrib/systemd/noesis.service` — same unit,
# same hardening (docs/policies.md § User separation), but generated from
# nix options.
#
# Usage from configuration.nix:
#   {
#     inputs.noesis.url = "github:Vaniell0/noesis";
#     ...
#     imports = [ inputs.noesis.nixosModules.default ];
#     services.noesis = {
#       enable = true;
#       # substrate/utility default to models built by this flake.
#       # personalVaultPath = "/home/alice/Documents";   # optional
#     };
#   }
#
# Single-tenant today. Multi-tenant (`services.noesis.instances = {...}`)
# is a planned refactor — the internal `mkNoesisConfig` helper is factored
# with that split in mind so per-instance attribute mapping is a rename,
# not a rewrite.

self:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.noesis;
  system = pkgs.stdenv.hostPlatform.system;

  runtimePkg    = cfg.package;
  substratePkg  = cfg.substrateModel;
  utilityPkg    = cfg.utilityModel;

  # ── Config file generation ────────────────────────────────────────────────
  #
  # Kept as a single helper so the multi-tenant refactor can call this per
  # instance without duplicating the TOML template.

  mkConfigToml = { statePath, lensRoot, substrateFile, utilityFile
                 , threads, httpThreads, httpBind
                 , utilityThreads, utilityKeepAliveSecs
                 , heartbeatPrompt, heartbeatSecs, maxGenTokens }:
    pkgs.writeText "noesis-config.toml" ''
      # Generated by services.noesis (NixOS module). Do not edit this file
      # directly — override options in configuration.nix instead.

      state_path        = "${statePath}"
      model_path        = "${substrateFile}"
      inference_backend = "rwkv-cpp"
      ${lib.optionalString (lensRoot != "") ''lens_root = "${lensRoot}"''}

      [rwkv_cpp]
      model_path              = "${substrateFile}"
      threads                 = ${toString threads}
      ${lib.optionalString (httpThreads != null) ''http_threads = ${toString httpThreads}''}
      ${lib.optionalString (httpBind != null) ''http_bind = "${httpBind}"''}
      ${lib.optionalString (utilityFile != null) ''
      utility_model_path      = "${utilityFile}"
      utility_threads         = ${toString utilityThreads}
      utility_keep_alive_secs = ${toString utilityKeepAliveSecs}
      ''}
      heartbeat_prompt        = "${heartbeatPrompt}"
      heartbeat_secs          = ${toString heartbeatSecs}
      max_gen_tokens          = ${toString maxGenTokens}
    '';

  substrateFile =
    if substratePkg != null then "${substratePkg}/model.bin"
    else cfg.substrateModelPath;

  utilityFile =
    if utilityPkg != null then "${utilityPkg}/model.bin"
    else cfg.utilityModelPath;

  configFile = mkConfigToml {
    statePath           = cfg.statePath;
    lensRoot            = cfg.lensRoot;
    inherit substrateFile utilityFile;
    threads             = cfg.threads;
    httpThreads         = cfg.httpThreads;
    httpBind            = cfg.httpBind;
    utilityThreads      = cfg.utilityThreads;
    utilityKeepAliveSecs = cfg.utilityKeepAliveSecs;
    heartbeatPrompt     = cfg.heartbeatPrompt;
    heartbeatSecs       = cfg.heartbeatSecs;
    maxGenTokens        = cfg.maxGenTokens;
  };

in {
  options.services.noesis = {
    enable = lib.mkEnableOption "noesis persistent cognitive runtime (system service)";

    # ── Packages ──────────────────────────────────────────────────────────

    package = lib.mkOption {
      type    = lib.types.package;
      default = self.packages.${system}.noesis-runtime;
      defaultText = lib.literalExpression "noesis.packages.\${system}.noesis-runtime";
      description = "The noesis-runtime package to install.";
    };

    substrateModel = lib.mkOption {
      type    = lib.types.nullOr lib.types.package;
      default = self.packages.${system}.noesis-model-g1h-29b;
      defaultText = lib.literalExpression "noesis.packages.\${system}.noesis-model-g1h-29b";
      description = ''
        Substrate model package (always-resident reasoning model). The
        package must expose <out>/model.bin in rwkv.cpp format. Set to
        null and provide substrateModelPath if the model lives outside
        the nix store.
      '';
    };

    substrateModelPath = lib.mkOption {
      type    = lib.types.nullOr lib.types.str;
      default = null;
      description = ''
        Absolute path to the substrate model .bin. Only consulted when
        substrateModel is null. The runtime refuses to start with no
        model configured (would idle silently); use one of these two
        options.
      '';
    };

    utilityModel = lib.mkOption {
      type    = lib.types.nullOr lib.types.package;
      default = self.packages.${system}.noesis-model-q5_1;
      defaultText = lib.literalExpression "noesis.packages.\${system}.noesis-model-q5_1";
      description = ''
        Utility model package (0.4B — emit-gate, classifier, formatter).
        Set to null to disable the utility path (runtime falls back to
        heuristics; principles.md P3 explicitly permits this).
      '';
    };

    utilityModelPath = lib.mkOption {
      type    = lib.types.nullOr lib.types.str;
      default = null;
      description = "Absolute path to the utility model .bin, when utilityModel is null.";
    };

    # ── Paths (aligned with docs/policies.md § Zone-level FS) ─────────────

    statePath = lib.mkOption {
      type    = lib.types.str;
      default = "/var/lib/noesis/store";
      description = ''
        State root — the LUKS/fscrypt mount point in the encrypted-store
        deployment (docs/policies.md § Disk encryption). Zones live
        directly under this path; calibration.toml is anchored here.
      '';
    };

    lensRoot = lib.mkOption {
      type    = lib.types.str;
      default = "/var/lib/noesis/store/lenses";
      description = ''
        Per-lens WKV snapshot root. Kept inside statePath so lens state
        (which IS cognition-in-flight) is encrypted along with zones.
        Set to "" to disable /lens endpoints.
      '';
    };

    # ── Threading ─────────────────────────────────────────────────────────

    threads = lib.mkOption {
      type    = lib.types.int;
      default = 1;
      description = ''
        Ambient/heartbeat rwkv-cpp context thread count. Keep low to
        respect the fan-off invariant (docs/policies.md § CPU budget).
        Use `noesis-runtime calibrate --thread-sweep` to find the
        machine-specific optimum, then override this option.
      '';
    };

    httpThreads = lib.mkOption {
      type    = lib.types.nullOr lib.types.int;
      default = 12;
      description = ''
        Interactive/HTTP rwkv-cpp context thread count. Default tuned
        for i5-1235U (peak ~19.6 tok/s on G1H 2.9B at 12 threads).
        null falls back to `threads`.
      '';
    };

    utilityThreads = lib.mkOption {
      type    = lib.types.int;
      default = 2;
      description = "Utility model context thread count.";
    };

    utilityKeepAliveSecs = lib.mkOption {
      type    = lib.types.int;
      default = 300;
      description = ''
        Idle seconds before the utility model is unloaded to free RAM.
        0 = always-resident (not recommended alongside a 2.9B substrate).
      '';
    };

    # ── HTTP shim ─────────────────────────────────────────────────────────

    httpBind = lib.mkOption {
      type    = lib.types.nullOr lib.types.str;
      default = "127.0.0.1:11435";
      description = ''
        host:port for the Ollama-shape HTTP shim (/api/generate,
        /v1/messages, /v1/chat/completions). null disables the shim
        (heartbeat + collectors only). Default binds localhost;
        exposing on the LAN also requires openFirewall = true.
      '';
    };

    openFirewall = lib.mkOption {
      type    = lib.types.bool;
      default = false;
      description = ''
        Open the httpBind port in the NixOS firewall. Default false —
        localhost bind is sufficient for CLI-integration on the same host.
      '';
    };

    # ── Heartbeat ─────────────────────────────────────────────────────────

    heartbeatPrompt = lib.mkOption {
      type    = lib.types.str;
      default = "You are noesis, a persistent cognitive runtime. Report your status in one sentence.";
      description = "Prompt the ambient drip loop periodically evaluates to keep the substrate warm.";
    };

    heartbeatSecs = lib.mkOption {
      type    = lib.types.int;
      default = 300;
      description = "Seconds between heartbeat evaluations.";
    };

    maxGenTokens = lib.mkOption {
      type    = lib.types.int;
      default = 20;
      description = "Max tokens the heartbeat may generate per tick.";
    };

    # ── Runtime resources ─────────────────────────────────────────────────

    memoryMax = lib.mkOption {
      type    = lib.types.str;
      default = "8G";
      description = ''
        systemd MemoryMax for the runtime process. 8G fits G1H 2.9B Q5_1
        (~2.6G) + working set + utility 0.4B. Bump for larger substrates.
      '';
    };

    # ── Personal vault + network ──────────────────────────────────────────

    personalVaultPath = lib.mkOption {
      type    = lib.types.nullOr lib.types.str;
      default = null;
      example = "/home/alice/Documents";
      description = ''
        Absolute path to the Obsidian vault (or any personal-doc tree) to
        graft into the runtime namespace read-only as /var/lib/noesis/vault.
        ProtectHome=yes hides /home/* by default; this bind grafts one
        subtree back in. null = no vault access. The runtime does not yet
        read this path automatically — the option is here so wiring the
        vault-ingest collector later needs no unit change.
      '';
    };

    extraIPAddressAllow = lib.mkOption {
      type    = lib.types.listOf lib.types.str;
      default = [];
      example = [ "api.anthropic.com" "time.cloudflare.com" ];
      description = ''
        Extra IPAddressAllow= entries beyond the default deny-all. Add
        Anthropic API host here when enabling H5 escalation, NTP if the
        host clock is untrusted, etc.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # ── Dedicated system user (policies.md § User separation) ─────────────

    users.groups.noesis = {};
    users.users.noesis = {
      isSystemUser = true;
      group        = "noesis";
      home         = "/var/lib/noesis";
      createHome   = false;   # StateDirectory handles this
      shell        = pkgs.shadow;   # /sbin/nologin equivalent
      description  = "noesis persistent cognitive runtime";
      # SupplementaryGroups in the unit itself; keeping the user record
      # minimal — the service-level groups are what actually take effect.
    };

    # ── Config skeleton in /etc ───────────────────────────────────────────

    environment.etc."noesis/config.toml".source = configFile;

    # ── Assertions ────────────────────────────────────────────────────────

    assertions = [
      {
        assertion = substrateFile != null;
        message = ''
          services.noesis: no substrate model configured. Set
          services.noesis.substrateModel to a package, or
          services.noesis.substrateModelPath to an absolute .bin path.
        '';
      }
    ];

    # ── Firewall ──────────────────────────────────────────────────────────

    networking.firewall.allowedTCPPorts = lib.optionals
      (cfg.openFirewall && cfg.httpBind != null)
      (let
        port = lib.toInt (lib.last (lib.splitString ":" cfg.httpBind));
      in [ port ]);

    # ── systemd unit (mirrors contrib/systemd/noesis.service) ─────────────

    systemd.services.noesis = {
      description = "noesis persistent cognitive runtime";
      documentation = [ "file:${runtimePkg}/share/doc/noesis/README.md" ];
      wantedBy = [ "multi-user.target" ];
      after    = [ "network.target" "local-fs.target" ];
      # State root may be a LUKS/fscrypt mount; systemd waits when the
      # mount unit exists, no-ops when it doesn't.
      unitConfig.RequiresMountsFor = cfg.statePath;

      serviceConfig = {
        Type              = "simple";
        User              = "noesis";
        Group             = "noesis";
        SupplementaryGroups = [ "input" "systemd-journal" ];

        # State + config skeleton. Multiple entries create the tree in
        # order; systemd honours ownership + mode. If cfg.statePath is
        # a mount, the mount hides the empty StateDirectory dir — fine.
        StateDirectory     = "noesis noesis/store noesis/store/lenses noesis/models";
        StateDirectoryMode = "0700";
        ConfigurationDirectory     = "noesis";
        ConfigurationDirectoryMode = "0750";
        LogsDirectory      = "noesis";

        Environment = [
          "NOESIS_CONFIG=/etc/noesis/config.toml"
          "RUST_LOG=info"
        ];

        ExecStart = "${runtimePkg}/bin/noesis-runtime";

        Restart        = "on-failure";
        RestartSec     = "5s";
        TimeoutStopSec = "30s";
        KillSignal     = "SIGTERM";
        KillMode       = "mixed";

        StandardOutput   = "journal";
        StandardError    = "journal";
        SyslogIdentifier = "noesis";

        # Hardening block — verbatim from policies.md § User separation.
        DynamicUser              = false;
        ProtectHome              = true;
        ProtectSystem            = "strict";
        ReadWritePaths           = [ "/var/lib/noesis" ];
        PrivateTmp               = true;
        NoNewPrivileges          = true;
        CapabilityBoundingSet    = "";
        AmbientCapabilities      = "";
        SystemCallFilter         = [ "@system-service" ];
        SystemCallErrorNumber    = "EPERM";
        RestrictAddressFamilies  = [ "AF_UNIX" "AF_INET" "AF_INET6" ];
        RestrictNamespaces       = true;
        RestrictSUIDSGID         = true;
        LockPersonality          = true;
        MemoryDenyWriteExecute   = true;
        ProtectClock             = true;
        ProtectKernelTunables    = true;
        ProtectKernelModules     = true;
        ProtectKernelLogs        = true;
        ProtectControlGroups     = true;
        ProtectProc              = "invisible";
        ProcSubset               = "pid";
        RestrictRealtime         = true;
        RemoveIPC                = true;
        UMask                    = "0077";

        # Network egress — deny all, then allow only what the operator
        # explicitly listed.
        IPAddressDeny  = "any";
        IPAddressAllow = cfg.extraIPAddressAllow;

        # Personal-vault bind (optional).
        BindReadOnlyPaths = lib.optional
          (cfg.personalVaultPath != null)
          "${cfg.personalVaultPath}:/var/lib/noesis/vault";

        # Runtime resource ceilings.
        MemoryMax = cfg.memoryMax;
      };
    };
  };
}
