//! Raw FFI bindings to rwkv.cpp.
//!
//! Generated by `build.rs` from `wrapper.h` (which is a thin
//! `#include <rwkv.h>`). Only `rwkv_*` symbols are surfaced; the ggml
//! internals are intentionally hidden.
//!
//! Safety of the wrapped calls is entirely the caller's business — use
//! the `noesis-rwkv` crate instead of touching this one directly unless
//! you're extending the wrapper itself.
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
