"""Pilot 100-step dry-run harness (Variant C hybrid, glaive-v2 primary).

Compute-independent bits: slice the first N rollouts out of the tokenised
train/val packs and write a pilot-config override that points the vendored
Lightning trainer at the sliced pack. Compute-dependent bit: `train_pilot.py`
still needs a CUDA GPU; run it separately.

Two subcommands:

    slice   — build training/tokenised/glaive_v2_{train,val}_dry100.pt
              (or whatever `--rollouts` is set to) plus
              training/config/pilot_dry100.yaml. Prints the exact
              train_pilot invocation for the smoke test.

    verify  — after the smoke run completes, walk `--run-dir` looking
              for the Lightning CSV logger's metrics file, extract the
              train CE trajectory over the first N steps, and fail loud
              (exit 1) if the trajectory is not monotone-decreasing
              once a small jitter tolerance is applied.

The plan (see ~/.claude/plans/verdant-anchoring-heron.md § Step 6) locks
in the dry-run as the gate before renting compute for the full pilot:
if 100 steps on 100 rollouts can't move CE downward, spending 10-14h of
4090 spot on the same corpus is throwing money at a broken pipeline.

Usage (from repo root):

    training/.venv/bin/python training/dry_run_100.py slice
    # run the smoke on a GPU box:
    training/.venv/bin/python training/train_pilot.py \\
        --config training/config/pilot_dry100.yaml
    # verify:
    training/.venv/bin/python training/dry_run_100.py verify \\
        --run-dir training/runs/pilot_g1d_glaive_v2_dry100
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import torch


HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent
TOKENISED_DIR = HERE / "tokenised"
CONFIG_DIR = HERE / "config"


def _slice_pack(pack_path: Path, n_rollouts: int, out_path: Path) -> dict:
    pack = torch.load(pack_path, map_location="cpu", weights_only=True)
    starts = pack["starts"]
    total = int(starts.numel())
    if total == 0:
        raise SystemExit(f"{pack_path}: no rollouts in pack")

    take = min(n_rollouts, total)
    # `end` is exclusive index into ids/loss_mask. If we consume the
    # whole pack, end is the tail; otherwise end is starts[take].
    end = int(starts[take].item()) if take < total else int(pack["ids"].numel())

    sliced = {
        "ids": pack["ids"][:end].clone(),
        "loss_mask": pack["loss_mask"][:end].clone(),
        "starts": starts[:take].clone(),
        "vocab": pack["vocab"],
    }

    n_supervised = int(sliced["loss_mask"].sum().item())
    total_tokens = int(sliced["ids"].numel())
    stats = {
        "path": str(out_path),
        "rollouts": take,
        "total_tokens": total_tokens,
        "supervised_tokens": n_supervised,
        "supervised_pct": (100.0 * n_supervised / max(1, total_tokens)),
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(sliced, out_path)
    return stats


def _write_config(
    base_config_path: Path,
    out_config_path: Path,
    train_pt_rel: str,
    val_pt_rel: str,
    run_name: str,
    n_steps: int,
) -> None:
    """Write pilot_dry100.yaml.

    We rewrite from scratch (rather than editing pilot.yaml in place)
    because the pilot config is the production-signal path — never mix
    the two. The dry-run YAML is disposable.
    """
    import yaml

    with open(base_config_path) as f:
        cfg = yaml.safe_load(f)

    # Point at sliced pack.
    cfg["corpus"]["tokenized_pt"] = train_pt_rel
    cfg["corpus"]["val_tokenized_pt"] = val_pt_rel

    # 100 steps is enough signal for a monotone-CE check. Vendored
    # train.py takes epoch_count; at accum=8 and batch_size=1 the
    # trainer sees ~800 forward passes per epoch on 100 rollouts,
    # depending on rollout length. Cap at 1 epoch — verify() reads
    # only the first n_steps rows anyway.
    cfg["training"]["epochs"] = 1
    cfg["training"]["eval_every_steps"] = max(25, n_steps // 4)
    cfg["training"]["ckpt_every_steps"] = max(50, n_steps // 2)
    cfg["training"]["early_stop_val_no_drop_by_steps"] = n_steps

    # Warmup capped so the first 100 steps see actual lr, not
    # near-zero. 10 is small enough to see movement, large enough to
    # avoid an instability spike at step 0.
    cfg["optimizer"]["warmup_steps"] = 10

    cfg["logging"]["run_name"] = run_name

    # Preserve state_reg block from base pilot.yaml. Dry-run is a
    # baseline CE-only smoke by default — the pilot.yaml default is
    # mode=off/alpha=0, which is exactly what we want here.

    header = (
        "# AUTO-GENERATED by training/dry_run_100.py — do NOT edit by hand.\n"
        "# Sliced dry-run over the first 100 glaive-v2 rollouts. Regenerate\n"
        "# via `python training/dry_run_100.py slice`.\n\n"
    )
    with open(out_config_path, "w") as f:
        f.write(header)
        yaml.safe_dump(cfg, f, sort_keys=False)


def _cmd_slice(args: argparse.Namespace) -> int:
    train_pack = TOKENISED_DIR / f"{args.rollouts}_train.pt"
    val_pack = TOKENISED_DIR / f"{args.rollouts}_val.pt"

    if not train_pack.exists():
        print(f"ERROR: {train_pack} not found. Run tokenize_rollouts.py first.",
              file=sys.stderr)
        return 1

    train_out = TOKENISED_DIR / f"{args.rollouts}_train_dry{args.n_rollouts}.pt"
    val_out = TOKENISED_DIR / f"{args.rollouts}_val_dry{args.n_rollouts}.pt"

    train_stats = _slice_pack(train_pack, args.n_rollouts, train_out)
    print(f"[slice] train → {train_stats['path']}")
    print(f"[slice]   rollouts={train_stats['rollouts']} "
          f"tokens={train_stats['total_tokens']} "
          f"supervised={train_stats['supervised_tokens']} "
          f"({train_stats['supervised_pct']:.1f}%)")

    if val_pack.exists():
        # Val slice: half as many rollouts (val is naturally 1/50th
        # size, so 50 rollouts is a full-ish smoke val batch).
        val_stats = _slice_pack(val_pack, max(1, args.n_rollouts // 2), val_out)
        print(f"[slice] val   → {val_stats['path']}")
        print(f"[slice]   rollouts={val_stats['rollouts']} "
              f"tokens={val_stats['total_tokens']} "
              f"supervised={val_stats['supervised_tokens']} "
              f"({val_stats['supervised_pct']:.1f}%)")
    else:
        print(f"[slice] val pack {val_pack} missing — dry config will point at train pack for val")
        val_out = train_out

    # Emit the override YAML.
    base_config = CONFIG_DIR / "pilot.yaml"
    out_config = CONFIG_DIR / f"pilot_dry{args.n_rollouts}.yaml"
    train_rel = str(train_out.relative_to(REPO_ROOT))
    val_rel = str(val_out.relative_to(REPO_ROOT))
    run_name = f"pilot_g1d_{args.rollouts}_dry{args.n_rollouts}"
    _write_config(base_config, out_config, train_rel, val_rel, run_name, args.n_steps)
    print(f"[slice] config → {out_config}")

    print()
    print("=== next: run the smoke on a CUDA box ===")
    print(f"  python training/train_pilot.py --config {out_config.relative_to(REPO_ROOT)}")
    print()
    print("=== then: verify CE trajectory ===")
    print(f"  python training/dry_run_100.py verify \\")
    print(f"      --run-dir training/runs/{run_name}")
    return 0


def _find_metrics_file(run_dir: Path) -> Path | None:
    """RWKV-PEFT's vendored trainer writes per-opt-step CE to
    `<run_dir>/loss_data.jsonl` (one JSON object per optimizer step
    with a ``loss`` key). Fall back to Lightning's `metrics.csv` in
    case the vendored logger changes in the future."""
    jsonl = list(run_dir.rglob("loss_data.jsonl"))
    if jsonl:
        jsonl.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        return jsonl[0]
    csv_candidates = list(run_dir.rglob("metrics.csv"))
    if csv_candidates:
        csv_candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        return csv_candidates[0]
    return None


def _extract_ce_trajectory(metrics_path: Path, n_steps: int) -> list[float]:
    """Read the train CE column from the metrics file."""
    ce: list[float] = []
    if metrics_path.suffix == ".jsonl":
        with open(metrics_path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    continue
                val = row.get("loss")
                if val is None:
                    continue
                try:
                    ce.append(float(val))
                except (TypeError, ValueError):
                    pass
                if len(ce) >= n_steps:
                    break
        return ce

    with open(metrics_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            for key in ("train_loss_step", "train/loss", "train_loss", "loss"):
                val = row.get(key, "")
                if val:
                    try:
                        ce.append(float(val))
                    except ValueError:
                        pass
                    break
            if len(ce) >= n_steps:
                break
    return ce


def _check_monotone(ce: list[float], tol: float = 0.10) -> tuple[bool, str]:
    """Head-vs-tail check with jitter tolerance.

    Full step-by-step monotonicity is too strict — real training curves
    zigzag by 5-20% at low steps because of batch composition variance.
    Compare the mean of the first 10% of steps to the mean of the last
    10%; require the drop to be at least `tol` × head_mean.
    """
    if len(ce) < 10:
        return False, f"too few CE points to judge ({len(ce)}); need ≥10"
    head_n = max(5, len(ce) // 10)
    tail_n = max(5, len(ce) // 10)
    head_mean = sum(ce[:head_n]) / head_n
    tail_mean = sum(ce[-tail_n:]) / tail_n
    drop = head_mean - tail_mean
    required = tol * head_mean
    ok = drop >= required
    msg = (
        f"head_mean={head_mean:.4f} tail_mean={tail_mean:.4f} "
        f"drop={drop:.4f} required≥{required:.4f} "
        f"(tolerance={tol:.0%} of head)"
    )
    return ok, msg


def _cmd_verify(args: argparse.Namespace) -> int:
    run_dir = Path(args.run_dir).resolve()
    if not run_dir.exists():
        print(f"ERROR: run_dir {run_dir} not found. Did the smoke run finish?",
              file=sys.stderr)
        return 1

    metrics_path = _find_metrics_file(run_dir)
    if metrics_path is None:
        print(f"ERROR: no loss_data.jsonl or metrics.csv under {run_dir}. "
              f"Inspect train_log.txt manually.", file=sys.stderr)
        return 1

    ce = _extract_ce_trajectory(metrics_path, args.n_steps)
    if not ce:
        print(f"ERROR: no train CE rows in {metrics_path}. Key/column name mismatch?",
              file=sys.stderr)
        return 1

    ok, msg = _check_monotone(ce, tol=args.tol)
    result = {
        "metrics_path": str(metrics_path),
        "ce_points": len(ce),
        "ce_head_first_5": ce[:5],
        "ce_tail_last_5": ce[-5:],
        "monotone_decreasing": ok,
        "detail": msg,
    }
    print(json.dumps(result, indent=2))

    if not ok:
        print("FAIL: CE trajectory did not drop far enough. Do NOT rent the "
              "full pilot on this pipeline — investigate before spending.",
              file=sys.stderr)
        return 1
    print("PASS: CE moved downward as expected. Safe to launch the full pilot.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_slice = sub.add_parser("slice", help="build dry-run pack + config")
    p_slice.add_argument("--rollouts", default="glaive_v2",
                         help="tokenised basename (default glaive_v2)")
    p_slice.add_argument("--n-rollouts", type=int, default=100,
                         help="rollouts to keep (default 100)")
    p_slice.add_argument("--n-steps", type=int, default=100,
                         help="smoke step budget for config knobs (default 100)")
    p_slice.set_defaults(func=_cmd_slice)

    p_verify = sub.add_parser("verify", help="check CE trajectory post-run")
    p_verify.add_argument("--run-dir", required=True,
                          help="training/runs/<run_name> to scan for metrics.csv")
    p_verify.add_argument("--n-steps", type=int, default=100,
                          help="cap CE point count at N (default 100)")
    p_verify.add_argument("--tol", type=float, default=0.10,
                          help="required head-vs-tail drop as fraction of head (default 0.10)")
    p_verify.set_defaults(func=_cmd_verify)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
