"""training/_common/corpus.py — shared corpus-combination utilities.

Mirrors experiments/_common/'s self-registering philosophy (one canonical
loader instead of copy-pasted-and-modified logic per script): found
`_load_rollouts`/`_pack_rollouts`/token-budget-sampling duplicated near
verbatim between combine_step9_corpus.py and combine_step10_corpus.py,
growing more ad-hoc each time a new source was mixed in (2 sources with
fixed fractions at step9 -> 7 sources with a general --fractions parser
at step10). Verified against combine_step10_corpus.py's actual
_load_rollouts/_pack_rollouts/_sample_to_budget before writing this, not
guessed from the .pt shape alone — the format is flat concatenated
ids/loss_mask/state_mask + a `starts` boundary index, not a padded batch
dimension.

Also fixes a real gap: no source's provenance (generated by noesis vs.
normalized from an external HF dataset, and which one) was ever recorded
anywhere but a hand-written docstring per combine script. `SourceSpec`
and the `_meta` block written by `save_combined_corpus` make that
queryable instead.
"""
from __future__ import annotations

import random
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Optional

import torch

Provenance = Literal["generated", "external-hf", "external-other"]


@dataclass
class SourceSpec:
    name: str
    path: Path | str
    fraction: float
    provenance: Provenance
    origin: str  # generated: the training/scripts/gen_*.py path. external: the HF dataset id / URL.


def load_rollouts(path: Path | str) -> list[dict]:
    """Split a combined .pt blob (flat ids/loss_mask/state_mask + `starts`
    boundary index) into a list of per-rollout dicts. Same logic as
    combine_step10_corpus.py's `_load_rollouts`, verified against it
    directly (not re-derived from the tensor shape)."""
    blob = torch.load(Path(path), map_location="cpu", weights_only=False)
    ids = blob["ids"]
    lm = blob["loss_mask"]
    sm = blob.get("state_mask", torch.zeros_like(lm))
    starts = blob["starts"].tolist()
    rollouts = []
    for i in range(len(starts) - 1):
        s, e = starts[i], starts[i + 1]
        rollouts.append({"ids": ids[s:e], "loss_mask": lm[s:e], "state_mask": sm[s:e]})
    return rollouts


def sample_to_budget(rollouts: list[dict], budget_tokens: int, rng: random.Random) -> tuple[list[dict], int]:
    """Shuffle + sample rollouts up to budget_tokens, truncating the last
    one to land exactly on budget rather than overshoot. Same behavior as
    combine_step10_corpus.py's `_sample_to_budget`, generalized off one
    script into something every combine script (and the next one) can
    call instead of re-writing."""
    shuffled = list(rollouts)
    rng.shuffle(shuffled)
    sampled: list[dict] = []
    used = 0
    for r in shuffled:
        remaining = budget_tokens - used
        if remaining <= 0:
            break
        n = int(r["ids"].numel())
        if n > remaining:
            r = {k: v[:remaining] for k, v in r.items()}
            n = remaining
        sampled.append(r)
        used += n
    return sampled, used


def pack_rollouts(rollouts: list[dict], vocab: str = "rwkv_vocab_v20230424") -> dict:
    """Inverse of load_rollouts: concatenate a list of per-rollout dicts
    back into the flat ids/loss_mask/state_mask/starts blob format the
    training loaders expect. Same as combine_step10_corpus.py's
    `_pack_rollouts`."""
    all_ids, all_lm, all_sm, starts = [], [], [], [0]
    for r in rollouts:
        n = int(r["ids"].numel())
        all_ids.append(r["ids"])
        all_lm.append(r["loss_mask"])
        all_sm.append(r["state_mask"])
        starts.append(starts[-1] + n)
    return {
        "ids": torch.cat(all_ids),
        "loss_mask": torch.cat(all_lm),
        "state_mask": torch.cat(all_sm),
        "starts": torch.tensor(starts, dtype=torch.long),
        "vocab": vocab,
    }


def combine_by_fraction(sources: list[SourceSpec], rng: random.Random) -> tuple[list[dict], dict]:
    """Load every source, sample each to its target fraction of the
    combined corpus's total tokens (anchor = sources[0], contributes all
    of itself; every other source's budget = anchor_tokens * (its
    fraction / anchor's fraction) — same convention combine_step9/10 used
    by hand). Returns (combined_rollouts_unshuffled_between_sources,
    per_source_meta) — caller shuffles after, same as the originals did,
    so a caller wanting a different final-shuffle policy still can.
    """
    if not sources:
        raise ValueError("combine_by_fraction: no sources given")
    anchor = sources[0]
    anchor_rolls = load_rollouts(anchor.path)
    anchor_tokens = sum(int(r["ids"].numel()) for r in anchor_rolls)

    combined = list(anchor_rolls)
    per_source_meta = {
        anchor.name: {
            "path": str(anchor.path), "n_rollouts": len(anchor_rolls), "n_tokens": anchor_tokens,
            "fraction_target": anchor.fraction, "provenance": anchor.provenance, "origin": anchor.origin,
        }
    }

    for s in sources[1:]:
        rolls = load_rollouts(s.path)
        budget = int(anchor_tokens * s.fraction / anchor.fraction)
        sampled, used = sample_to_budget(rolls, budget, rng)
        combined.extend(sampled)
        per_source_meta[s.name] = {
            "path": str(s.path), "n_rollouts": len(sampled), "n_tokens": used,
            "fraction_target": s.fraction, "provenance": s.provenance, "origin": s.origin,
        }

    return combined, per_source_meta


def save_combined_corpus(rollouts: list[dict], out_path: Path | str, per_source_meta: dict,
                          script: str, vocab: str = "rwkv_vocab_v20230424") -> Path:
    """Pack + save, plus a provenance record (via `training._common.provenance`,
    the shared schema every pipeline stage uses — not a separate one-off
    shape) recording which sources went in, at what fraction, and each
    one's own provenance — the thing that previously only lived in each
    combine script's hand-written docstring."""
    from training._common.provenance import make_record, save_provenance

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    blob = pack_rollouts(rollouts, vocab=vocab)

    n_tok = int(blob["ids"].numel())
    n_sup = int(blob["loss_mask"].sum())
    n_state = int(blob["state_mask"].sum())
    torch.save(blob, out_path)

    record = make_record(
        name=out_path.stem, stage="combine", provenance="generated",
        origin="combine_by_fraction", script=script, out_path=out_path,
        n_rows=len(rollouts), n_tokens=n_tok, n_supervised_tokens=n_sup,
        sources=per_source_meta, extra={"n_state_supervised_tokens": n_state},
    )
    save_provenance(record)
    return out_path
